config/routes.rb
ChessShop::Application.routes.draw do

  devise_for :admins

  resources :categories do
    get :manage, :on => :collection
    post :rebuild, :on => :collection
  end

  resources :items do
    post :upload_from_excel, :on =>  :collection
    get :load_from_excel, :on => :collection  
  end

  root :to => 'items#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable  
  attr_accessible :email, :password, :password_confirmation
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :image
  belongs_to :attachable, :polymorphic => true
  mount_uploader  :image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  include TheSortableTree::Scopes
  acts_as_nested_set
  has_many    :items
  belongs_to  :version
  attr_accessible :name, :parent_id, :version
  
  validates :name, :presence => true
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible  :title, :price, :category_id, :attachments, :attachments_attributes
  
  belongs_to  :category
  belongs_to  :verion
  has_many :attachments, :as => :attachable
  accepts_nested_attributes_for :attachments
  validates :title, :presence => true
  validates :category, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
end

app/models/version.rb
class Version < ActiveRecord::Base
  attr_accessible :name
  has_many  :categories
  has_many  :items, :through => :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_locale
  protect_from_forgery
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { :locale => I18n.locale }
  end
protected
  
  def get_version
    Version.find_by_name(I18n.locale)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include TheSortableTreeController::Rebuild
  before_filter :authenticate_admin!, :except => [:show, :index]
    
  def index
    @categories = get_version.categories.nested_set.all
  end
  
  def manage
    @categories = get_version.categories.nested_set.all
  end
  
  def show
    @category = get_category(params[:id])
    @items = @category.items
  end

  def new
    @category = Category.new
    @version = get_version
  end

  def edit
    @category = get_category(params[:id])
    @version = get_version
  end

  def create
    @category = Category.new(params[:category])
    @category.version = get_version
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @category = get_category(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category = get_category(params[:id])
    no_category = Category.find_by_name_and_version_id('--', get_version.id)
    for item in @category.items
      item.update_attributes(:category_id => no_category.id)
    end
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
  
  private
  
  def get_category(id)
    Category.find(id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_admin!, :except => [:show, :index]
  
  def index
    @items = get_version.items
  end

  def show
    @item = get_item(params[:id])
  end

  def new
    @item = Item.new
    @categories = get_version.categories
  end

  def edit
    @item = get_item(params[:id])
    @categories = get_version.categories
  end

  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        @categories = get_version.categories
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @item = get_item(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        @categories = get_version.categories
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = get_item(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end
  
  def load_from_excel
  end
  
  def upload_from_excel
    file = ExcelUploader.new
    file.store!(params[:excel_file])
    sheet1 = Spreadsheet.open("#{file.store_path}").worksheets[0]
    @items = []
    counter = 0
    @errors = Hash.new
    sheet1.each do |row|
      counter += 1
      item = Item.new
      item.title = row[0]
      item.category = Category.find_by_name(row[1])
      item.price = row[2]
      if item.valid?
        @items << item
      else
        @errors[counter.to_s] = item.errors
      end
    end
    @items.each {|i| i.save} unless @errors.any? 
    file.remove!
  end
  
  private
  
  def get_item(id)
    Item.find(id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/_category_tree.haml
#category_tree
  -while category
    %li.category 
      &laquo;
      = link_to category.name, category
    - category = category.parent
  %li.category
    = link_to t(:all_categories), categories_path

app/views/categories/_form.haml
= form_for(@category) do |f|
  -if @category.errors.any?
    #error_explanation
      %h2 
        =pluralize(@category.errors.count, "error")
        prohibited this category from being saved:
      %ul
        -@category.errors.full_messages.each do |msg|
          %li
            =msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :parent_id
    = f.collection_select :parent_id, @version.categories, :id, :name, {:include_blank => true}
  .action
    = f.submit

app/views/categories/edit.haml
%h1 Editing category
= render 'form'

app/views/categories/index.haml
- content_for :css do
  = stylesheet_link_tag 'the_sortable_tree_min', :media => :screen

%p= link_to raw('&larr; back'), root_path

= sortable_tree @categories, :title => :name, :path => 'the_sortable_tree_min'

app/views/categories/manage.haml
- content_for :css do
  = stylesheet_link_tag 'the_sortable_tree', :media => :screen
- content_for :js do
  = javascript_include_tag 'jquery.ui.nestedSortable'

%p= link_to raw('&larr; ' + t(:nav_back)), root_path

= sortable_tree @categories, :title => :name, :new_url => new_category_path, :max_levels => 4

app/views/categories/new.haml
%h1 New category
= render 'form'

app/views/categories/show.haml
#notice
  = notice

= render 'category_tree', :category => @category
%br
= render '/items/items', :items => @items

app/views/categories/the_sortable_tree/_children.html.haml
= content_tag :ol, raw(children)

app/views/categories/the_sortable_tree/_controls.html.haml
-# EDIT
- edit = link_to '', polymorphic_url(opts[:namespace] + [node], :action => :edit), :title => t('.edit_this'), :class => 'button edit'
-# DELETE
- if opts[:has_children]
  - delete =  link_to('', url_for(opts[:namespace] + [node]),
    :title    =>  t('.delete'),
    :method   =>  :delete,
    :confirm  =>  t('.delete_confirm'),
    :class    =>  'button delete')
- else
  - delete =  link_to('', '#',
    :title    =>  t('.cant_be_deleted'),
    :onclick  =>  "alert('#{t('.delete_nested_elements')}')",
    :class    =>  'button undeleted')
-# OUTPUT
= edit + delete

app/views/categories/the_sortable_tree/_js_init_sortable_tree.html.haml
:javascript
  $(function(){
    $('ol.sortable').nestedSortable({
      disableNesting: 'no-nest',
      forcePlaceholderSize: true,
      handle: 'i.handle',
      helper: 'clone',
      items: 'li',
      maxLevels: #{opts[:max_levels]},
      opacity: .6,
      placeholder: 'placeholder',
      revert: 250,
      tabSize: 25,
      tolerance: 'pointer',
      toleranceElement: '> div'
    })
  });

app/views/categories/the_sortable_tree/_js_on_update_tree.html.haml
:javascript
  $(function(){
    $('ol.sortable').sortable({
      update: function(event, ui){
        parent_id = ui.item.parent().parent().attr('id');
        item_id = ui.item.attr('id');
        prev_id = ui.item.prev().attr('id');
        next_id = ui.item.next().attr('id');
        sortable_tree(item_id, parent_id, prev_id, next_id);
      }
    });
  });

app/views/categories/the_sortable_tree/_js_rebuild_ajax.html.haml
:javascript
  function sortable_tree(item_id, parent_id, prev_id, next_id){
    jQuery.ajax({
      type:       'POST',
      dataType:   'script',
      url:        '#{url_for(:controller => opts[:klass].pluralize, :action => :rebuild)}',
      data:       { id: item_id, parent_id: parent_id, prev_id: prev_id, next_id: next_id },

      beforeSend: function(xhr){ $('.nested_set i.handle').hide() },
      success:    function(data, status, xhr){ $('.nested_set i.handle').show() },
      error:      function(xhr, status, error){ alert(error) }
    });
  }

app/views/categories/the_sortable_tree/_link.html.haml
- title     = node.send opts[:title]
- handle    = content_tag :i, '', :class => :handle
- link      = link_to(title, url_for(opts[:namespace] + [node]), :title => title)
- controls  = render(:partial  =>  "#{opts[:path]}/controls", :locals  =>  { :node => node, :opts => opts })
- controls  = content_tag(:b, controls, :class => :controls)
- element   = handle + controls + link
%div{ :class => "link#{' root' if root}" }= element

app/views/categories/the_sortable_tree/_new.html.haml
- image = image_tag('iconza/blue/add.png', :class => :nested_set_new_image) + ' '
- link  = link_to(image + t('.create'), opts[:new_url])
.nested_set_new= link

app/views/categories/the_sortable_tree/_node.html.haml
%li{ :id => "#{node.send(opts[:id])}_#{opts[:klass]}" }
  = raw render(:partial => "#{opts[:path]}/link", :locals => {:opts => opts, :root => root, :node => node})
  = render(:partial => "#{opts[:path]}/children", :locals => {:opts => opts, :parent => node, :children => children}) unless children.blank?

app/views/categories/the_sortable_tree/_tree.html.haml
= render :partial => "#{opts[:path]}/new", :locals => { :opts => opts }
- unless tree.empty?
  = render :partial => "#{opts[:path]}/js_init_sortable_tree", :locals => { :opts => opts }
  = render :partial => "#{opts[:path]}/js_on_update_tree"
  = render :partial => "#{opts[:path]}/js_rebuild_ajax", :locals => { :opts => opts }
  %ol.ui-sortable.sortable.nested_set{ :id => "#{opts[:klass]}_nested_set" }= raw tree

app/views/items/_form.haml
=nested_form_for @item, :html => {:multipart => true} do |f|
  =if @item.errors.any?
    #error_explanation
      %h2 
        = pluralize(@item.errors.count, "error")
        prohibited this item from being saved:
      %ul
        -@item.errors.full_messages.each do |msg|
          %li
            =msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :category
    = f.collection_select :category_id, @categories, :id, :name
  .field
    = f.label :price
    = f.text_field :price
  =f.fields_for :attachments do |attachment_form|
    .field
      = attachment_form.label :image
      = attachment_form.file_field :image
    = attachment_form.link_to_remove 'Remove image'
  = f.link_to_add 'Add image', :attachments
  .actions
    = f.submit

app/views/items/_items.haml
%h1 
  = t(:listing_items)
%ul.items
  - for item in items
    %li
      = link_to item do
        - if item.attachments.any?
          = image_tag(item.attachments[item.main_image].image.thumb.url) 
        - else
          = image_tag("no_image.jpg")
      %span.title= link_to truncate(item.title, :length => 20), item
      = link_to item.category.name, category_path(item.category)
      %span.price= item.price

app/views/items/edit.haml
%h1 Editing item

= render 'form'

= link_to('Show', @item) |
= link_to('Back', items_path)

app/views/items/index.haml
= render '/items/items', :items => @items

app/views/items/load_from_excel.haml
=form_tag '/items/upload_from_excel', :multipart => true
%p= file_field_tag  'excel_file'
%p= submit_tag t(:load_excel)

app/views/items/new.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/show.haml
%p
  #notice
    = notice
= render '/categories/category_tree', :category => @item.category
%br
%p
  %b Title:
  = @item.title
%p
  %b Price
  = @item.price
%ul.images
  -for attachment in @item.attachments
    %li
      =image_tag(attachment.image.thumb.url)

app/views/items/upload_from_excel.haml
- unless @errors.empty?
  %h2 Failure
  #error_explanation
    %h2 
      =pluralize(@errors.count, "error")
      prevent this excel export:
    %ul
      -@errors.each do |error|
        %li 
          Problems in line number 
          =error[0]
          -error[1].full_messages.each do |msg|
            %p 
              = msg
- else
  %h2 Success
  = render '/items/items', :items => @items

app/views/layouts/application.haml
!!!
%html
  %head
    %title ChessShop
    %meta{:charset => "utf-8"}
    =stylesheet_link_tag  :application
    =javascript_include_tag :application
    = csrf_meta_tags
    =yield :css
    =yield :js
  %body
    #header
      =render 'shared/header'
    #main
      =yield

app/views/shared/_header.haml
%h2 
  = link_to t(:wellcome), root_path
  %span{:style => 'float:right;'}
    = t(:set_language)
    = link_to 'EN', url_for(:locale => 'en')
    = link_to 'RU', url_for(:locale => 'ru')
- if admin_signed_in?
  %li{:style => "list-style: none"}
    = link_to t(:item_new), new_item_path
    - unless !@item || @item.new_record?
      = link_to t(:item_edit), edit_item_path(@item)
      = link_to t(:item_delete), @item, :confirm => t(:item_confirm), :method => :delete
    = link_to t(:load_excel), load_from_excel_items_path
    = link_to t(:category_new), new_category_path
    = link_to t(:category_manage), manage_categories_path
    = link_to t(:logout), destroy_admin_session_path, :method => :delete
- else
  %li{:style => "list-style: none"}
    = link_to t(:login), new_admin_session_path